theme: jekyll-theme-cayman
title : S&P 500 Data Puller
tagline: Site Tagline
author :
	  name : Name Lastname
	  email : blah@email.test
	  github : username
	  twitter : username
	  feedburner : feedname
